/* One departmental demo: planning, engineer records and serviceable tags. */
"use strict";
const OPS_KEY="tslms-engineering-demo-v2";
STORE.users.push({user:"p.chirwa",pass:"eng123",role:"engineer",name:"P. Chirwa",title:"Aircraft Engineer"});
STORE.profiles=STORE.users.map((u,i)=>({user:u.user,id:`AZ-DEM-${101+i}`,name:u.name,department:u.role==="engineer"?"Aircraft Engineering":u.role==="stores"?"Technical Stores":"Quality Assurance",specialty:u.role==="engineer"?"Airframe & powerplant":u.title,shift:"Day shift",authority:"Demo authority"}));
STORE.components.forEach((c,i)=>Object.assign(c,{totalHours:c.hours+1000,totalCycles:c.cycles+600,lastOverhaul:relativeDate(-365),basis:"overhaul",release:`DEMO-REL-${101+i}`,originJob:`WO-${24500+i}`,modState:"No modification recorded",rectification:"Inspected / serviceable",authority:"Demo authority",releaseDate:relativeDate(-30),flights:c.cycles,totalFlights:c.cycles+600,fLimit:c.cLimit,retireHours:20000,retireCycles:15000,condition:c.reg==="Stores"?"Quarantined":"Installed"}));
STORE.resources=[{id:"BAY-1",name:"Hangar bay 1",kind:"Bay",condition:"Available"},{id:"BAY-2",name:"Hangar bay 2",kind:"Bay",condition:"Available"},{id:"TOOL-1",name:"Engine hoist",kind:"Tool",condition:"Available"},{id:"TOOL-2",name:"Torque tooling kit",kind:"Tool",condition:"Available"},{id:"TOOL-3",name:"Hydraulic test rig",kind:"Tool",condition:"Out of service"}];
STORE.jobs=[{id:"PLAN-1001",title:"Brake inspection / replacement",reg:"Z-WPV",engineer:"t.ndlovu",bay:"BAY-1",tool:"TOOL-2",start:demoDate+"T08:00",end:demoDate+"T12:00",status:"Scheduled",wo:"WO-24518",by:"t.ndlovu"}];
STORE.audit=[];
try {const saved=JSON.parse(localStorage.getItem(OPS_KEY));if(saved&&saved.version===2){for(const k of ["fleet","components","profiles","jobs","audit"])if(Array.isArray(saved[k]))STORE[k]=saved[k];}}catch(e){console.warn("Demo storage unavailable",e.message);}
function persistOps(){try{localStorage.setItem(OPS_KEY,JSON.stringify({version:2,fleet:STORE.fleet,components:STORE.components,profiles:STORE.profiles,jobs:STORE.jobs,audit:STORE.audit}));}catch(e){toast("warn","Storage unavailable","Changes are available for this session only.");}}
function auditOps(action,reference,details){STORE.audit.unshift({at:new Date().toISOString(),by:session.user,name:session.name,action,reference,details});persistOps();}
function requireEngineer(){if(!session||session.role!=="engineer"){toast("warn","Engineer workflow","Sign in as a maintenance engineer to update technical records.");return false;}return true;}
function profileOf(user){return STORE.profiles.find(p=>p.user===user);}
function viewProfiles(){
 $("viewSub").textContent="Individual departmental profiles, assigned work and engineer record history. Demo accounts only.";
 $("viewActions").innerHTML=`<button class="btn btn-accent" onclick="editProfile()">Edit my profile</button>`;
 $("viewBody").innerHTML=`<div class="fleet-grid">${STORE.profiles.map(p=>`<article class="aircraft-card"><div class="aircraft-top"><span class="aircraft-symbol">${esc(p.name.split(' ').map(x=>x[0]).join('').slice(0,2))}</span>${engTag(p.user===session.user?"MY PROFILE":"TEAM")}</div><h3 style="font-size:20px">${esc(p.name)}</h3><p>${esc(p.id)} · ${esc(p.department)}</p><div class="attention-row"><div><b>${esc(p.specialty)}</b><small>${esc(p.shift)} · ${esc(p.authority)}</small></div></div><small>${STORE.jobs.filter(j=>j.engineer===p.user&&j.status!=="Complete").length} assigned jobs · ${STORE.audit.filter(a=>a.by===p.user).length} record entries</small></article>`).join("")}</div>${engPanel("Record history",engTable(["Date","Person","Action","Reference","Details"],STORE.audit.slice(0,30).map(a=>`<tr><td>${esc(a.at.slice(0,16).replace('T',' '))} UTC</td><td>${esc(a.name)}</td><td>${esc(a.action)}</td><td>${esc(a.reference)}</td><td>${esc(a.details)}</td></tr>`).join("")))}`;
}
function editProfile(){const p=profileOf(session.user);engineeringModal("My departmental profile",`<form onsubmit="event.preventDefault();saveProfile()"><label for="profileName">Display name</label><input id="profileName" required maxlength="60" value="${esc(p.name)}"><label for="profileSkill">Specialty</label><input id="profileSkill" required maxlength="80" value="${esc(p.specialty)}"><label for="profileShift">Shift</label><select id="profileShift"><option ${p.shift==='Day shift'?'selected':''}>Day shift</option><option ${p.shift==='Night shift'?'selected':''}>Night shift</option></select><p class="form-note">Profile ID and department remain linked to your demo sign-in.</p><button type="submit" class="btn-primary">Save profile</button></form>`);}
function saveProfile(){const p=profileOf(session.user),name=$("profileName").value.trim(),specialty=$("profileSkill").value.trim();if(!name||!specialty)return;p.name=name;p.specialty=specialty;p.shift=$("profileShift").value;session.name=name;$("userName").textContent=name;auditOps("Profile updated",p.id,p.shift);closeModal();route("#profiles");}
function viewResources(){
 $("viewSub").textContent="Plan maintenance jobs around aircraft, engineers, hangar bays and shared tooling. Overlapping assignments are blocked.";
 $("viewActions").innerHTML=session.role==="engineer"?`<button class="btn btn-accent" onclick="openPlan()">+ Plan maintenance</button>`:"";
 $("viewBody").innerHTML=`<div class="kpi-grid">${engMetric("Open maintenance jobs",STORE.jobs.filter(j=>j.status!=="Complete").length,"scheduled + in progress")}${engMetric("Engineers",STORE.users.filter(u=>u.role==="engineer").length,"individual demo accounts")}${engMetric("Available assets",STORE.resources.filter(r=>r.condition==="Available").length,"bays & tooling")}</div>${engPanel("Maintenance work plan",engTable(["Work order / Task","Aircraft","Engineer","Window","Bay / Tool","Status","Action"],STORE.jobs.map(j=>`<tr><td><b>${esc(j.wo)}</b><small class="table-sub">${esc(j.title)}</small></td><td>${esc(j.reg)}</td><td>${esc(profileOf(j.engineer)?.name||j.engineer)}</td><td>${esc(j.start.replace('T',' '))}<small class="table-sub">to ${esc(j.end.replace('T',' '))} · local station time</small></td><td>${esc(j.bay)} / ${esc(j.tool)}</td><td>${engTag(j.status,j.status==="Complete"?"ok":"info")}</td><td>${session.role==="engineer"&&j.status!=="Complete"?`<button class="btn btn-sm" onclick="advancePlan('${j.id}')">${j.status==="Scheduled"?"Start work":"Complete task"}</button>`:"—"}</td></tr>`).join("")))}<div style="margin-top:20px">${engPanel("Resource availability",engTable(["Asset","Type","Condition"],STORE.resources.map(r=>`<tr><td>${r.name}</td><td>${r.kind}</td><td>${engTag(r.condition,r.condition==="Available"?"ok":"danger")}</td></tr>`).join("")))}</div><p class="form-note">Completing a planning task records progress only. It does not release an aircraft or reset component limits.</p>`;
}
function resourceConflict(candidate,jobs=STORE.jobs){return jobs.find(j=>j.status!=="Complete"&&candidate.start<j.end&&candidate.end>j.start&&["reg","engineer","bay","tool"].some(k=>candidate[k]===j[k]));}
function openPlan(){if(!requireEngineer())return;engineeringModal("Plan maintenance work",`<form onsubmit="event.preventDefault();savePlan()"><label for="planTask">Task</label><input id="planTask" required maxlength="100" placeholder="e.g. C-check work package"><label for="planWo">Work order</label><input id="planWo" required maxlength="40" placeholder="WO-24530"><label for="planReg">Aircraft</label><select id="planReg">${STORE.fleet.map(a=>`<option>${a.reg}</option>`).join("")}</select><label for="planEngineer">Assigned engineer</label><select id="planEngineer">${STORE.users.filter(u=>u.role==="engineer").map(u=>`<option value="${u.user}">${esc(profileOf(u.user).name)}</option>`).join("")}</select><label for="planBay">Bay</label><select id="planBay">${STORE.resources.filter(r=>r.kind==="Bay"&&r.condition==="Available").map(r=>`<option value="${r.id}">${r.name}</option>`).join("")}</select><label for="planTool">Tool</label><select id="planTool">${STORE.resources.filter(r=>r.kind==="Tool"&&r.condition==="Available").map(r=>`<option value="${r.id}">${r.name}</option>`).join("")}</select><label for="planStart">Start (local station time)</label><input id="planStart" type="datetime-local" required value="${demoDate}T13:00"><label for="planEnd">End (local station time)</label><input id="planEnd" type="datetime-local" required value="${demoDate}T17:00"><p id="planError" class="field-err" role="alert"></p><button class="btn-primary" type="submit">Save maintenance plan</button></form>`);}
function savePlan(){if(!requireEngineer())return;const j={id:`PLAN-${Date.now()}`,title:$("planTask").value.trim(),wo:$("planWo").value.trim(),reg:$("planReg").value,engineer:$("planEngineer").value,bay:$("planBay").value,tool:$("planTool").value,start:$("planStart").value,end:$("planEnd").value,status:"Scheduled",by:session.user};if(!j.title||!j.wo||!j.start||!j.end||j.start>=j.end){$("planError").textContent="Enter a task, work order and an end time after the start.";return;}const conflict=resourceConflict(j);if(conflict){$("planError").textContent=`Assignment overlaps ${conflict.wo}. Choose another time or resource.`;return;}STORE.jobs.push(j);auditOps("Maintenance planned",j.wo,j.title);closeModal();route("#resources");}
function advancePlan(id){if(!requireEngineer())return;const j=STORE.jobs.find(x=>x.id===id);if(!j||j.status==="Complete")return;j.status=j.status==="Scheduled"?"In progress":"Complete";auditOps("Work plan updated",j.wo,j.status);route("#resources");}
function viewServiceable(){
 $("viewSub").textContent="Digital component tags based on your Air Zimbabwe examples: origin job, serial, ATA, usage, removal limits, release and installation records.";
 $("viewActions").innerHTML=session.role==="engineer"?`<button class="btn btn-accent" onclick="openComponentLog()">+ Engineer log entry</button>`:"";
 $("viewBody").innerHTML=`<div class="fleet-grid">${STORE.components.map(c=>{const s=componentState(c);return `<article class="aircraft-card"><div class="aircraft-top">${engTag(c.condition,c.condition==="Quarantined"?"danger":"ok")}${engTag(s.status,s.status==="OVERDUE"?"danger":"info")}</div><h3 style="font-size:19px">${esc(c.sn)}</h3><p>${esc(c.pn)} · ${esc(c.reg)}</p><div class="aircraft-data"><div><small>Remaining hours</small><b>${s.hours.toLocaleString()}</b></div><div><small>Remaining cycles</small><b>${s.cycles}</b></div></div><button class="btn" onclick="openServiceable('${c.sn}')">Open digital tag →</button></article>`;}).join("")}</div>`;
}
function openServiceable(sn){const c=STORE.components.find(x=>x.sn===sn);if(!c)return;const p=STORE.parts.find(x=>x.pn===c.pn),s=componentState(c);const fields={"Code":c.sn,"Origin job no.":c.originJob,"Description":p?.name||c.pn,"Part no.":c.pn,"Serial no.":c.sn,"ATA":p?.ata||"—","Nature of rectification":c.rectification,"Mod. state":c.modState,"Hours since overhaul (TSO)":c.hours,"Cycles since overhaul (CSO)":c.cycles,"Flights since overhaul":c.flights,"Total hours since new (TSN)":c.totalHours,"Total cycles since new (CSN)":c.totalCycles,"Last overhaul":c.lastOverhaul,"Overhaul hour interval":c.hLimit,"Overhaul cycle interval":c.cLimit,"Overhaul flight interval":c.fLimit,"Lifetime hour limit":c.retireHours,"Lifetime cycle limit":c.retireCycles,"Remaining hours":s.hours,"Remaining cycles":s.cycles,"Remaining flights":s.flights,"Calendar removal date":c.due,"Release no.":c.release,"Release date":c.releaseDate,"Authority":c.authority,"Fitted to":c.reg,"Position":c.position,"Condition":c.condition};engineeringModal("Digital component tag",`<div class="digital-tag"><div class="eyebrow">AIR ZIMBABWE / DEMONSTRATION</div><h2>${c.condition==="Quarantined"?"QUARANTINED":"COMPONENT RECORD"}</h2><div class="dl">${Object.entries(fields).map(([k,v])=>`<div><div class="k">${k}</div><div class="v">${esc(v??"—")}</div></div>`).join("")}</div></div><p class="form-note">Digital representation of the supplied tag; not an authorised release certificate. Handwritten values have not been imported.</p>${session.role==="engineer"?`<button class="btn-primary" onclick="openComponentLog('${c.sn}')">Update engineer record</button>`:""}`);}
function openComponentLog(sn=""){if(!requireEngineer())return;engineeringModal("Engineer component log",`<form onsubmit="event.preventDefault();saveComponentLog()"><label for="logSerial">Component serial</label><select id="logSerial" onchange="fillComponentLog()">${STORE.components.map(c=>`<option value="${c.sn}" ${c.sn===sn?"selected":""}>${c.sn} · ${c.pn}</option>`).join("")}</select><label for="logHours">Hours since overhaul (TSO)</label><input id="logHours" type="number" min="0" step="0.1" required><label for="logCycles">Cycles since overhaul (CSO)</label><input id="logCycles" type="number" min="0" step="1" required><label for="logFlights">Flights since overhaul</label><input id="logFlights" type="number" min="0" step="1" required><label for="logRelease">Release / job reference</label><input id="logRelease" required maxlength="60"><label for="logNotes">Work / rectification notes</label><input id="logNotes" required maxlength="160"><label for="logOverhaul">Entry type</label><select id="logOverhaul"><option value="usage">Usage update</option><option value="overhaul">Recorded overhaul completed</option></select><p class="form-note">Usage counters cannot decrease. An overhaul starts a new TSO/CSO interval and preserves total life. Component limits stay unchanged.</p><p id="logError" class="field-err" role="alert"></p><button type="submit" class="btn-primary">Save signed demo entry</button></form>`);fillComponentLog();}
function fillComponentLog(){const c=STORE.components.find(x=>x.sn===$("logSerial").value);$("logHours").value=c.hours;$("logCycles").value=c.cycles;$("logFlights").value=c.flights;$("logRelease").value=c.release;}
function applyComponentLog(c,values,overhaul){const {hours,cycles,flights}=values;if(![hours,cycles,flights].every(Number.isFinite)||hours<0||cycles<0||flights<0||!Number.isInteger(cycles)||!Number.isInteger(flights))throw Error("Use non-negative hours and whole cycles / flights.");if(overhaul){if(hours!==0||cycles!==0||flights!==0)throw Error("Enter zero since-overhaul counters for a recorded overhaul.");c.lastOverhaul=demoDate;/* Calendar expiry remains unchanged until a supporting record sets a new date. */}else{if(hours<c.hours||cycles<c.cycles||flights<c.flights)throw Error("Usage counters cannot decrease. Use an overhaul entry where applicable.");c.totalHours=Math.round((c.totalHours+hours-c.hours)*10)/10;c.totalCycles+=cycles-c.cycles;c.totalFlights+=flights-c.flights;}c.hours=hours;c.cycles=cycles;c.flights=flights;}
function saveComponentLog(){if(!requireEngineer())return;const c=STORE.components.find(x=>x.sn===$("logSerial").value),reference=$("logRelease").value.trim(),notes=$("logNotes").value.trim(),overhaul=$("logOverhaul").value==="overhaul";if(!reference||!notes){$("logError").textContent="Enter a reference and work notes.";return;}try{applyComponentLog(c,{hours:Number($("logHours").value),cycles:Number($("logCycles").value),flights:Number($("logFlights").value)},overhaul);}catch(e){$("logError").textContent=e.message;return;}c.release=reference;c.rectification=notes;c.authority=profileOf(session.user).authority;c.releaseDate=demoDate;auditOps(overhaul?"Overhaul recorded":"Component counters updated",c.sn,`${reference}: ${notes}; TSO ${c.hours} / CSO ${c.cycles}`);closeModal();route("#components");toast("ok","Engineer entry saved","Remaining life recalculated; total life retained.");}
// Remaining life is deterministic arithmetic from limits, not an AI guess.
const basicComponentState=componentState;
componentState=function(c){const s=basicComponentState(c);if(c.retireHours!=null)s.hours=Math.min(s.hours,c.retireHours-c.totalHours);if(c.retireCycles!=null)s.cycles=Math.min(s.cycles,c.retireCycles-c.totalCycles);s.flights=c.fLimit==null?null:c.fLimit-c.flights;if(s.hours<=0||s.cycles<=0||s.days<=0||s.flights!==null&&s.flights<=0)s.status="OVERDUE";else if(s.hours<=200||s.cycles<=100||s.days<=30||s.flights!==null&&s.flights<=100)s.status="DUE SOON";return s;};
const originalSaveUtilisation=saveUtilisation;
saveUtilisation=function(){if(!requireEngineer())return;const reg=$("utilReg").value,h=Number($("utilHours").value),c=Number($("utilCycles").value);if(!Number.isFinite(h)||!Number.isInteger(c)||h<0||c<0){toast("warn","Invalid utilisation","Use non-negative hours and whole cycles.");return;}STORE.components.filter(x=>x.reg===reg).forEach(x=>{x.totalHours=Math.round((x.totalHours+h)*10)/10;x.totalCycles+=c;x.flights+=c;x.totalFlights+=c;});originalSaveUtilisation();auditOps("Aircraft utilisation",reg,`+${h} FH / +${c} FC; flights assumed equal to cycles in demo`);};
const originalDoLogin=doLogin;
doLogin=function(user,pass){const u=STORE.users.find(x=>x.user.toLowerCase()===user.toLowerCase()&&x.pass===pass);if(u)u.name=profileOf(u.user)?.name||u.name;originalDoLogin(user,pass);};
