/* Research-informed, local demonstration of engineering quality controls. */
"use strict";
STORE.calibrations=[{id:"CAL-DEMO-1",tool:"TOOL-2",serial:"TQ-24018",date:relativeDate(-180),due:relativeDate(14),certificate:"DEMO-CAL-24018",lab:"Demo metrology laboratory",standard:"DEMO-MASTER-TQ-01",method:"Torque comparison · N·m",environment:"22 °C",tolerance:4,uncertainty:1,found:1.5,left:1,by:"k.moyo",at:new Date().toISOString()}];
STORE.lifeReviews=[];STORE.labTests=[];STORE.qualityFindings=[];
try{const q=JSON.parse(localStorage.getItem(OPS_KEY));if(q?.version===2)for(const key of ["calibrations","lifeReviews","labTests","qualityFindings"])if(Array.isArray(q[key]))STORE[key]=q[key];}catch(e){console.warn("Quality records unavailable",e.message);}
persistOps=function(){try{const q={version:2};for(const key of ["fleet","components","profiles","jobs","audit","movements","defects","planningRates","parts","calibrations","lifeReviews","labTests","qualityFindings"])q[key]=STORE[key];localStorage.setItem(OPS_KEY,JSON.stringify(q));}catch(e){toast("warn","Local storage unavailable","Export records before leaving this session.");}};
function calibrationScreen(error,uncertainty,tolerance){if(![error,uncertainty,tolerance].every(Number.isFinite)||uncertainty<0||tolerance<=0)throw Error("Enter finite results, non-negative uncertainty and a positive tolerance.");return Math.abs(error)+uncertainty<=tolerance;}
function currentCalibration(tool,date=demoDate){const c=STORE.calibrations.find(x=>x.tool===tool&&x.date<=date);if(!c)return {status:STORE.resources.find(x=>x.id===tool)?.condition!=="Available"?"Out of service":"No calibration",usable:false};const resource=STORE.resources.find(x=>x.id===tool);const open=STORE.qualityFindings.some(f=>f.tool===tool&&f.status!=="Closed");const valid=calibrationScreen(c.left,c.uncertainty,c.tolerance)&&c.due>date&&resource?.condition==="Available"&&!open;return {record:c,usable:valid,status:open?"Impact review open":resource?.condition!=="Available"?"Out of service":c.due<=date?"Overdue":!calibrationScreen(c.left,c.uncertainty,c.tolerance)?"Quarantined":Math.ceil((Date.parse(c.due)-Date.parse(date))/86400000)<=30?"Due soon":"Current"};}
function validQualityDate(value){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value;}
function validateCalibration(c){for(const key of ["certificate","lab","standard","method","environment","serial"])if(!c[key]?.trim())throw Error("Complete certificate, laboratory, standard, method, conditions and serial fields.");if(!STORE.resources.some(r=>r.id===c.tool&&r.kind==="Tool"))throw Error("Select a registered tool.");if(!validQualityDate(c.date)||!validQualityDate(c.due)||c.date>demoDate||c.due<=demoDate||c.due<=c.date)throw Error("Calibration must be dated today or earlier; next due date must be in the future.");calibrationScreen(c.found,c.uncertainty,c.tolerance);calibrationScreen(c.left,c.uncertainty,c.tolerance);return c;}
function addCalibration(c){validateCalibration(c);const previous=STORE.calibrations.find(x=>x.tool===c.tool);if(previous&&c.date<previous.date)throw Error("New calibration cannot predate the latest record.");const failed=!calibrationScreen(c.found,c.uncertainty,c.tolerance);STORE.calibrations.unshift(c);if(failed){const affected=STORE.jobs.filter(j=>j.tool===c.tool&&j.status!=="Scheduled"&&j.start.slice(0,10)>=(previous?.date||"0000-00-00")&&j.start.slice(0,10)<=c.date).map(j=>j.wo);STORE.qualityFindings.unshift({id:`FIND-${Date.now()}`,tool:c.tool,certificate:c.certificate,opened:c.at,affected,status:"Open",reason:"As-found screening exceeded tolerance; review work since previous calibration.",notes:""});}return failed;}
function viewCalibration(){const tools=STORE.resources.filter(r=>r.kind==="Tool"),usable=tools.filter(t=>currentCalibration(t.id).usable).length;$("viewSub").textContent="Certificate history, due dates and out-of-tolerance impact review linked to maintenance tooling.";$("viewActions").innerHTML=`${session.role==="inspector"?'<button class="btn btn-accent" onclick="openCalibration()">+ Record calibration</button>':""}<button class="btn" onclick="exportTechnical()">Export record pack</button>`;$("viewBody").innerHTML=`<div class="eng-metrics">${engMetric("Registered tools",tools.length,"Controlled equipment")}${engMetric("Available for work",usable,"Calibration and quality gates satisfied")}${engMetric("Impact reviews",STORE.qualityFindings.filter(f=>f.status!=="Closed").length,"As-found failures require disposition")}</div>${engPanel("Calibration register",engTable(["Tool / serial","Status","Next due","Certificate / reference","Action"],tools.map(t=>{const s=currentCalibration(t.id),c=s.record;return `<tr><td><b>${esc(t.name)}</b><small class="table-sub">${esc(c?.serial||t.id)}</small></td><td>${engTag(s.status,s.usable?"ok":"danger")}</td><td>${esc(c?.due||"—")}</td><td>${esc(c?.certificate||"Missing")}<small class="table-sub">${esc(c?.standard||"Calibration required")}</small></td><td><button class="btn btn-sm" onclick="openCalibrationHistory('${t.id}')">History</button></td></tr>`;}).join("")))}${engPanel("Out-of-tolerance impact reviews",engTable(["Tool / finding","Potentially affected work","Status","Disposition"],STORE.qualityFindings.map(f=>`<tr><td>${esc(f.tool)}<small class="table-sub">${esc(f.certificate)}</small></td><td>${esc(f.affected.join(", ")||"No recorded completed / started work in lookback window")}</td><td>${engTag(f.status,f.status==="Closed"?"ok":"danger")}</td><td>${esc(f.notes)}${f.status!=="Closed"&&session.role==="inspector"?`<button class="btn btn-sm" onclick="openImpact('${f.id}')">Review impact</button>`:""}</td></tr>`).join("")))}<p class="form-note">Demo screening: |error| + expanded uncertainty ≤ stated tolerance, in the same units. This conservative example is not a replacement for the approved laboratory decision rule or maintenance data. Tool types and limits require organisation approval.</p>`;}
function openCalibrationHistory(tool){engineeringModal("Calibration history",engTable(["Date / next due","Certificate / lab","Method / reference","Results","Recorded by"],STORE.calibrations.filter(c=>c.tool===tool).map(c=>`<tr><td>${esc(c.date)} / ${esc(c.due||"No calendar limit")}</td><td>${esc(c.certificate)}<small class="table-sub">${esc(c.lab)}</small></td><td>${esc(c.method)}<small class="table-sub">${esc(c.standard)} · ${esc(c.environment)}</small></td><td>Found ${c.found}; left ${c.left}; U ${c.uncertainty}; tolerance ±${c.tolerance}</td><td>${esc(c.by)}</td></tr>`).join("")));}
function openCalibration(){if(!technicalRole(["inspector"]))return;engineeringModal("Record calibration certificate",`<form onsubmit="event.preventDefault();saveCalibration()"><label for="calTool">Tool</label><select id="calTool">${STORE.resources.filter(t=>t.kind==="Tool").map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join("")}</select><div class="form-grid">${[["Serial","serial","text",""],["Certificate reference","certificate","text",""],["Laboratory","lab","text",""],["Master standard / traceability reference","standard","text",""],["Method and measurement units","method","text",""],["Environmental conditions","environment","text",""],["Calibration date","date","date",demoDate],["Next due date","due","date",relativeDate(365)],["As-found error (worst point)","found","number","0"],["As-left error (worst point)","left","number","0"],["Expanded uncertainty","uncertainty","number","1"],["Permitted ± tolerance","tolerance","number","4"]].map(([label,id,type,value])=>`<div><label for="cal_${id}">${label}</label><input id="cal_${id}" type="${type}" value="${value}" ${type==="number"?'step="any"':""} required maxlength="100"></div>`).join("")}</div><p class="form-note">Copy values from the actual demonstration certificate in common units. An as-found failure opens an impact review; an as-left failure blocks use.</p><p id="calError" class="field-err" role="alert"></p><button class="btn-primary">Save calibration record</button></form>`);}
function saveCalibration(){if(!technicalRole(["inspector"]))return;const c={id:`CAL-${Date.now()}`,tool:$("calTool").value,by:session.user,at:new Date().toISOString()};for(const k of ["serial","certificate","lab","standard","method","environment","date","due"])c[k]=$("cal_"+k).value.trim();for(const k of ["found","left","uncertainty","tolerance"])c[k]=Number($("cal_"+k).value);try{addCalibration(c);}catch(e){$("calError").textContent=e.message;return;}auditOps("Calibration recorded",c.tool,c.certificate);closeModal();route("#calibration");}
function openImpact(id){if(!technicalRole(["inspector"]))return;engineeringModal("Calibration impact disposition",`<form onsubmit="event.preventDefault();closeImpact('${id}')"><p>Review affected work orders and record the assessment, reinspection or follow-up work references. Closing this review does not certify an aircraft release.</p><label for="impactNotes">Assessment and corrective action references</label><textarea id="impactNotes" required maxlength="500"></textarea><button class="btn-primary">Record disposition</button></form>`);}
function closeImpact(id){if(!technicalRole(["inspector"]))return;const f=STORE.qualityFindings.find(x=>x.id===id),notes=$("impactNotes").value.trim();if(!f||!notes)return;f.notes=notes;f.status="Closed";f.closedBy=session.user;f.closedAt=new Date().toISOString();auditOps("Calibration impact reviewed",f.tool,notes);closeModal();route("#calibration");}
function lifeSnapshot(c){return JSON.stringify([c.sn,c.pn,c.reg,c.position,c.hours,c.cycles,c.flights,c.totalHours,c.totalCycles,c.totalFlights,c.hLimit,c.cLimit,c.fLimit,c.retireHours,c.retireCycles,c.due,c.lastOverhaul,c.release,c.condition]);}
function lifeReviewState(c){const r=STORE.lifeReviews.find(x=>x.sn===c.sn);if(!r)return "Awaiting inspection";if(r.outcome==="Discrepancy")return "Discrepancy open";if(r.snapshot!==lifeSnapshot(c))return "Changed since inspection";return componentState(c).status==="OVERDUE"?"Limit reached after review":"Reviewed current record";}
function recordLifeReview(c,outcome,reference,notes){if(!["Verified","Discrepancy"].includes(outcome)||!reference.trim()||!notes.trim())throw Error("Enter evidence reference, outcome and inspection notes.");if(outcome==="Verified"&&componentState(c).status==="OVERDUE")throw Error("An exhausted life limit requires a discrepancy and engineering action.");if(![c.hours,c.cycles,c.totalHours,c.totalCycles].every(v=>Number.isFinite(v)&&v>=0)||!Number.isInteger(c.cycles)||!Number.isInteger(c.totalCycles))throw Error("Component counters require reconciliation before review.");if(c.totalHours<c.hours||c.totalCycles<c.cycles)throw Error("Since-new counters cannot be below since-overhaul counters.");const r={id:`LIFE-${Date.now()}`,sn:c.sn,snapshot:lifeSnapshot(c),counters:{hours:c.hours,cycles:c.cycles,totalHours:c.totalHours,totalCycles:c.totalCycles},remaining:componentState(c),outcome,reference,notes,by:session.user,at:new Date().toISOString()};STORE.lifeReviews.unshift(r);return r;}
function viewLifeInspection(){const changed=STORE.components.filter(c=>lifeReviewState(c)!=="Reviewed current record");$("viewSub").textContent="Independent inspector review of serial identity, supporting records, total life and overhaul intervals. Changes invalidate the current review.";$("viewActions").innerHTML='<button class="btn" onclick="exportTechnical()">Export record pack</button>';$("viewBody").innerHTML=`<div class="eng-metrics">${engMetric("Awaiting action",changed.length,"Unreviewed, changed or discrepant")}${engMetric("Review history",STORE.lifeReviews.length,"Inspector evidence and counter snapshots")}</div>${engPanel("Component life inspection queue",engTable(["Serial / aircraft","TSO / CSO","TSN / CSN","Remaining","Inspection","Action"],STORE.components.map(c=>{const s=componentState(c),r=lifeReviewState(c);return `<tr><td><b>${esc(c.sn)}</b><small class="table-sub">${esc(c.reg)}</small></td><td>${c.hours} / ${c.cycles}</td><td>${c.totalHours} / ${c.totalCycles}</td><td>${Number.isFinite(s.hours)?s.hours:"N/A"} FH / ${Number.isFinite(s.cycles)?s.cycles:"N/A"} FC<small class="table-sub">${esc(c.due||"No calendar interval")}</small></td><td>${engTag(r,r==="Reviewed current record"?"ok":"warnb")}</td><td><button class="btn btn-sm" onclick="openServiceable('${c.sn}')">Tag</button> ${session.role==="inspector"?`<button class="btn btn-sm btn-accent" onclick="openLifeInspection('${c.sn}')">Inspect life</button>`:""}</td></tr>`;}).join("")))}${engPanel("Inspection evidence history",engTable(["Serial / timestamp","Outcome","Evidence","Inspector / notes"],STORE.lifeReviews.map(r=>`<tr><td>${esc(r.sn)}<small class="table-sub">${esc(r.at)}</small></td><td>${engTag(r.outcome,r.outcome==="Verified"?"ok":"danger")}</td><td>${esc(r.reference)}<small class="table-sub">TSO ${r.counters.hours}; TSN ${r.counters.totalHours}</small></td><td>${esc(r.by)}<small class="table-sub">${esc(r.notes)}</small></td></tr>`).join("")))}`;}
function openLifeInspection(sn){if(!technicalRole(["inspector"]))return;const c=STORE.components.find(x=>x.sn===sn),s=componentState(c);engineeringModal("Inspect component life record",`<form onsubmit="event.preventDefault();saveLifeInspection('${sn}')"><p><b>${esc(sn)}</b> · ${esc(c.reg)} · ${engTag(s.status,s.status==="OVERDUE"?"danger":"info")}</p><p>TSO ${c.hours} / CSO ${c.cycles}; TSN ${c.totalHours} / CSN ${c.totalCycles}. Remaining ${Number.isFinite(s.hours)?s.hours:"N/A"} hours, ${Number.isFinite(s.cycles)?s.cycles:"N/A"} cycles and ${Number.isFinite(s.days)?s.days:"N/A"} calendar days.</p><label><input id="lifeIdentity" type="checkbox" required> Serial identity, fitment and release reference checked</label><label><input id="lifeCounters" type="checkbox" required> Logbook totals, overhaul evidence and approved limits reconciled</label><label for="lifeReference">Evidence / logbook / work reference</label><input id="lifeReference" required maxlength="120"><label for="lifeOutcome">Review outcome</label><select id="lifeOutcome"><option>Verified</option><option>Discrepancy</option></select><label for="lifeNotes">Inspector findings / required action</label><textarea id="lifeNotes" required maxlength="500"></textarea><p id="lifeError" role="alert" class="field-err"></p><button class="btn-primary">Record independent inspection</button></form>`);}
function saveLifeInspection(sn){if(!technicalRole(["inspector"]))return;if(!$("lifeIdentity").checked||!$("lifeCounters").checked)return;const c=STORE.components.find(x=>x.sn===sn);try{recordLifeReview(c,$("lifeOutcome").value,$("lifeReference").value.trim(),$("lifeNotes").value.trim());}catch(e){$("lifeError").textContent=e.message;return;}auditOps("Component life inspected",sn,$("lifeOutcome").value);closeModal();route("#life-inspection");}
const labMethods=["Fluid / particle analysis","Material failure analysis","Material compatibility","Flammability investigation","Ultrasonic (UT)","Eddy current (ET)","Penetrant (PT)","Magnetic particle (MT)","Thermographic (TT)","Radiographic (RT)"];
function viewLaboratory(){ $("viewSub").textContent="Sample custody, report references and inspector disposition linked to component serials. Laboratory results do not automatically extend component life.";$("viewActions").innerHTML=`${["engineer","inspector"].includes(session.role)?'<button class="btn btn-accent" onclick="openLabRequest()">+ Request investigation</button>':""}<button class="btn" onclick="exportTechnical()">Export record pack</button>`;$("viewBody").innerHTML=`<div class="workflow-strip"><span>01 Investigation request</span><span>02 Sample custody</span><span>03 Laboratory report</span><span>04 Inspector disposition</span></div>${engPanel("Laboratory & NDT investigations",engTable(["Sample / serial","Method / reason","Status","Report / disposition","Action"],STORE.labTests.map(t=>`<tr><td><b>${esc(t.id)}</b><small class="table-sub">${esc(t.sn)} · ${esc(t.reg)}</small></td><td>${esc(t.method)}<small class="table-sub">${esc(t.reason)}</small></td><td>${engTag(t.status,t.result==="Action needed"?"danger":"info")}</td><td>${esc(t.report||"Pending")}<small class="table-sub">${esc(t.findings||"")} ${esc(t.disposition||"")}</small></td><td>${["engineer","inspector"].includes(session.role)&&t.status==="Requested"?`<button class="btn btn-sm" onclick="openLabStep('${t.id}','receive')">Receive sample</button>`:""}${session.role==="inspector"&&t.status==="Sample received"?`<button class="btn btn-sm" onclick="openLabStep('${t.id}','report')">Record report</button>`:""}${session.role==="inspector"&&t.status==="Report recorded"?`<button class="btn btn-sm" onclick="openLabStep('${t.id}','review')">Inspect result</button>`:""}</td></tr>`).join("")))}<p class="form-note">Research inspired by Lufthansa Technik laboratory services. These are workflow records for external qualified testing; no laboratory integration or automated NDT diagnosis is claimed.</p>`;}
function openLabRequest(){if(!technicalRole(["engineer","inspector"]))return;engineeringModal("Request laboratory investigation",`<form onsubmit="event.preventDefault();saveLabRequest()"><label for="labSerial">Component</label><select id="labSerial">${STORE.components.map(c=>`<option>${esc(c.sn)}</option>`).join("")}</select><label for="labMethod">Investigation method</label><select id="labMethod">${labMethods.map(m=>`<option>${m}</option>`).join("")}</select><label for="labReason">Problem / work order reference</label><textarea id="labReason" required maxlength="300"></textarea><button class="btn-primary">Create investigation</button></form>`);}
function saveLabRequest(){if(!technicalRole(["engineer","inspector"]))return;const c=STORE.components.find(x=>x.sn===$("labSerial").value),reason=$("labReason").value.trim();if(!c||!reason)return;const t={id:`LAB-${Date.now()}`,sn:c.sn,reg:c.reg,method:$("labMethod").value,reason,status:"Requested",by:session.user,at:new Date().toISOString()};STORE.labTests.unshift(t);auditOps("Laboratory investigation requested",t.id,reason);closeModal();route("#laboratory");}
function openLabStep(id,step){if(!technicalRole(step==="receive"?["engineer","inspector"]:["inspector"]))return;engineeringModal(step==="receive"?"Record sample custody":step==="report"?"Record laboratory report":"Inspector laboratory disposition",`<form onsubmit="event.preventDefault();saveLabStep('${id}','${step}')"><label for="labStepRef">${step==="receive"?"Sample ID, recipient and custody reference":step==="report"?"Laboratory report / approved method reference":"Disposition / follow-up work reference"}</label><input id="labStepRef" required maxlength="160">${step==="report"?'<label for="labResult">Report outcome</label><select id="labResult"><option>No adverse finding</option><option>Action needed</option></select>':""}<label for="labStepNotes">${step==="review"?"Assessment and engineering action":"Notes / findings"}</label><textarea id="labStepNotes" required maxlength="500"></textarea><button class="btn-primary">Save ${step}</button></form>`);}
function saveLabStep(id,step){if(!technicalRole(step==="receive"?["engineer","inspector"]:["inspector"]))return;const t=STORE.labTests.find(x=>x.id===id),ref=$("labStepRef").value.trim(),notes=$("labStepNotes").value.trim();if(!t||!ref||!notes)return;const expected={receive:"Requested",report:"Sample received",review:"Report recorded"};if(t.status!==expected[step])return;if(step==="receive"){t.custody=ref;t.receivedBy=session.user;t.receivedAt=new Date().toISOString();t.custodyNotes=notes;t.status="Sample received";}else if(step==="report"){t.report=ref;t.findings=notes;t.result=$("labResult").value;t.reportedBy=session.user;t.reportedAt=new Date().toISOString();t.status="Report recorded";}else{t.disposition=`${ref}: ${notes}`;t.reviewedBy=session.user;t.reviewedAt=new Date().toISOString();t.status="Reviewed";if(t.result==="Action needed"&&t.reg!=="Stores")STORE.defects.unshift({ref:`DEF-${Date.now()}`,reg:t.reg,ata:STORE.parts.find(p=>p.pn===STORE.components.find(c=>c.sn===t.sn)?.pn)?.ata||"00",description:`${t.id} / ${t.sn}: ${t.findings}`,priority:"Grounded",status:"Open",by:session.user,at:new Date().toISOString(),reference:ref});}auditOps("Laboratory workflow",id,`${step}: ${ref}`);closeModal();route("#laboratory");}
// Planning gates use the scheduled end date; starting work rechecks today's validity.
const savePlanWithoutCalibration=savePlan;
savePlan=function(){if(!technicalRole(["engineer","planner"]))return;const s=currentCalibration($("planTool").value,$("planEnd").value.slice(0,10));if(!s.usable){$("planError").textContent=`Tool unavailable at planned completion: ${s.status}. Choose calibrated equipment or record calibration first.`;return;}savePlanWithoutCalibration();};
const advancePlanWithoutCalibration=advancePlan;
advancePlan=function(id){if(!requireEngineer())return;const j=STORE.jobs.find(x=>x.id===id);if(j?.status==="Scheduled"&&!currentCalibration(j.tool).usable){toast("warn","Work start blocked","Tool calibration or impact review requires attention.");return;}advancePlanWithoutCalibration(id);};
function adverseLabOpen(sn){const report=STORE.labTests.find(t=>t.sn===sn&&t.report);return !!report&&(report.result==="Action needed"||report.status!=="Reviewed");}
const qualityWithoutLab=canQualityApprove;
canQualityApprove=function(c){qualityWithoutLab(c);if(adverseLabOpen(c.sn))throw Error("An unresolved laboratory report requires engineering disposition before serviceable inspection.");return true;};
const installWithoutLifeReview=validateInstall;
validateInstall=function(c,reg,position,components=STORE.components){installWithoutLifeReview(c,reg,position,components);if(adverseLabOpen(c.sn))throw Error("Unresolved laboratory findings block installation.");if(lifeReviewState(c)!=="Reviewed current record")throw Error("An inspector must verify the current component life record before installation.");return true;};
const aircraftWithoutQuality=aircraftState;
aircraftState=function(a){const base=aircraftWithoutQuality(a);if(STORE.components.some(c=>c.reg===a.reg&&(lifeReviewState(c)==="Discrepancy open"||adverseLabOpen(c.sn))))return "QUALITY HOLD";return base;};
const flightWithoutQuality=flightAssessment;
flightAssessment=function(reg,hours,cycles,date){const reasons=flightWithoutQuality(reg,hours,cycles,date);if(STORE.components.some(c=>c.reg===reg&&lifeReviewState(c)==="Discrepancy open"))reasons.push("Unresolved inspector life-record discrepancy");if(STORE.components.some(c=>c.reg===reg&&adverseLabOpen(c.sn)))reasons.push("Laboratory report requires engineering review");return reasons;};
exportTechnical=function(){const data={schema:"tslms-technical-demo-v2",exportedAt:new Date().toISOString()};for(const key of ["fleet","components","jobs","movements","defects","audit","calibrations","lifeReviews","labTests","qualityFindings","resources","profiles","planningRates"])data[key]=STORE[key];const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="tslms-engineering-record-pack.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const overviewWithoutQuality=viewEngineeringDashboard;
viewEngineeringDashboard=function(){
 overviewWithoutQuality();
 const pending=STORE.components.filter(c=>lifeReviewState(c)!=="Reviewed current record").length;
 const blocked=STORE.resources.filter(r=>r.kind==="Tool"&&!currentCalibration(r.id).usable).length;
 $("viewBody").insertAdjacentHTML("beforeend",engPanel("Engineering quality readiness",`<div class="workflow-strip"><span>${pending} component life reviews need attention</span><span>${blocked} tools unavailable for controlled work</span><span>${STORE.labTests.filter(t=>t.status!=="Reviewed").length} laboratory investigations pending</span></div><div class="row"><button class="btn" onclick="route('#calibration')">Calibration & tool control</button><button class="btn" onclick="route('#life-inspection')">Inspector life review</button><button class="btn" onclick="route('#laboratory')">Laboratory & NDT</button></div>`));
};
