/* Working local engineering workflows; not an operational airworthiness system. */
"use strict";
STORE.movements=[];STORE.defects=[];STORE.planningRates={};
try{const saved=JSON.parse(localStorage.getItem(OPS_KEY));if(saved?.version===2){for(const k of ["movements","defects"])if(Array.isArray(saved[k]))STORE[k]=saved[k];if(saved.planningRates)STORE.planningRates=saved.planningRates;if(Array.isArray(saved.parts))STORE.parts=saved.parts;}}catch(e){console.warn("Technical records unavailable",e.message);}
const persistBasicOps=persistOps;
persistOps=function(){try{localStorage.setItem(OPS_KEY,JSON.stringify({version:2,fleet:STORE.fleet,components:STORE.components,profiles:STORE.profiles,jobs:STORE.jobs,audit:STORE.audit,movements:STORE.movements,defects:STORE.defects,planningRates:STORE.planningRates,parts:STORE.parts}));}catch(e){toast("warn","Local storage unavailable","Records are held for this session only.");}};
function technicalRole(roles){if(!session||!roles.includes(session.role)){toast("warn","Department workflow",`This action requires ${roles.join(" or ")} sign-in.`);return false;}return true;}
function remainingAt(c,date){const state=componentState(c);return {...state,days:Math.ceil((Date.parse(date+"T00:00:00Z")-Date.parse(new Date().toISOString().slice(0,10)+"T00:00:00Z"))/86400000)};}
function recordMovement(action,c,from,to,reference){STORE.movements.unshift({id:`MOV-${Date.now()}`,at:new Date().toISOString(),action,sn:c.sn,pn:c.pn,from,to,reference,by:session.user});auditOps(action,c.sn,`${from} → ${to}; ${reference}`);}
function viewLifecycle(){
 $("viewSub").textContent="Serial-controlled receipt, quality inspection, installation and removal. Aircraft utilisation follows installed components only.";
 $("viewActions").innerHTML=`${session.role==="stores"?`<button class="btn btn-accent" onclick="openReceipt()">+ Receive component</button>`:""}<button class="btn" onclick="exportTechnical()">Export technical records</button>`;
 $("viewBody").innerHTML=`<div class="workflow-strip"><span>01 Receive & quarantine</span><span>02 Quality inspection</span><span>03 Install on aircraft</span><span>04 Track / remove</span></div>${engPanel("Component lifecycle register",engTable(["Serial / Part","Location","Condition","Life status","Release reference","Workflow"],STORE.components.map(c=>`<tr><td><b>${esc(c.sn)}</b><small class="table-sub">${esc(c.pn)}</small></td><td>${esc(c.reg)}<small class="table-sub">${esc(c.position)}</small></td><td>${engTag(c.condition,c.condition==="Quarantined"?"danger":c.condition==="Serviceable"?"ok":"info")}</td><td>${engTag(componentState(c).status,componentState(c).status==="OVERDUE"?"danger":"info")}</td><td>${esc(c.release)}</td><td><div class="row lifecycle-actions"><button class="btn btn-sm" onclick="openServiceable('${c.sn}')">Record</button>${c.reg==="Stores"&&c.condition==="Quarantined"&&session.role==="inspector"?`<button class="btn btn-sm" onclick="openQuality('${c.sn}')">Inspect</button>`:""}${c.reg==="Stores"&&c.condition==="Serviceable"&&session.role==="engineer"?`<button class="btn btn-sm btn-accent" onclick="openInstall('${c.sn}')">Install</button>`:""}${c.reg!=="Stores"&&session.role==="engineer"?`<button class="btn btn-sm" onclick="openRemoval('${c.sn}')">Remove</button>`:""}</div></td></tr>`).join("")))}<div style="margin-top:20px">${engPanel("Installation & custody history",engTable(["Timestamp","Serial","Action","From → To","Reference","Recorded by"],STORE.movements.map(m=>`<tr><td>${esc(m.at.slice(0,16).replace('T',' '))} UTC</td><td>${esc(m.sn)}</td><td>${esc(m.action)}</td><td>${esc(m.from)} → ${esc(m.to)}</td><td>${esc(m.reference)}</td><td>${esc(profileOf(m.by)?.name||m.by)}</td></tr>`).join("")))}</div>`;
}
function openReceipt(){if(!technicalRole(["stores"]))return;engineeringModal("Receive serialised component",`<form onsubmit="event.preventDefault();saveReceipt()"><label for="receiptPart">Catalogue part</label><select id="receiptPart">${STORE.parts.map(p=>`<option value="${p.pn}">${p.pn} · ${p.name}</option>`).join("")}</select><label for="receiptSerial">Unique serial number</label><input id="receiptSerial" required maxlength="40" pattern="[A-Za-z0-9_-]+"><label for="receiptRelease">Release document reference</label><input id="receiptRelease" required maxlength="60"><label for="receiptJob">Origin job / goods receipt</label><input id="receiptJob" required maxlength="40"><div class="form-grid"><div><label for="receiptHours">TSO hours</label><input id="receiptHours" type="number" min="0" step="0.1" required value="0"></div><div><label for="receiptCycles">CSO cycles / flights</label><input id="receiptCycles" type="number" min="0" step="1" required value="0"></div><div><label for="receiptTotalHours">Total hours since new</label><input id="receiptTotalHours" type="number" min="0" step="0.1" required value="0"></div><div><label for="receiptTotalCycles">Total cycles since new</label><input id="receiptTotalCycles" type="number" min="0" step="1" required value="0"></div><div><label for="receiptHourLimit">Overhaul hour interval</label><input id="receiptHourLimit" type="number" min="1" step="0.1" required></div><div><label for="receiptCycleLimit">Overhaul cycle interval</label><input id="receiptCycleLimit" type="number" min="1" required></div><div><label for="receiptRetireHours">Lifetime hour limit</label><input id="receiptRetireHours" type="number" min="1" required></div><div><label for="receiptRetireCycles">Lifetime cycle limit</label><input id="receiptRetireCycles" type="number" min="1" required></div></div><label for="receiptOverhaul">Last overhaul date</label><input id="receiptOverhaul" type="date" required value="${demoDate}"><label for="receiptDue">Calendar removal date</label><input id="receiptDue" type="date" required><p class="form-note">Use demonstration limits from your sample records. Receipt enters quarantine pending a separate Quality Inspector review.</p><p id="receiptError" role="alert" class="field-err"></p><button class="btn-primary" type="submit">Receive into quarantine</button></form>`);}
function validateReceipt(c,components=STORE.components){if(!/^[A-Za-z0-9_-]+$/.test(c.sn)||components.some(x=>x.sn.toUpperCase()===c.sn.toUpperCase()))throw Error("Use a unique serial containing letters, numbers, hyphens or underscores.");for(const k of ["hours","cycles","totalHours","totalCycles","hLimit","cLimit","retireHours","retireCycles"])if(!Number.isFinite(c[k])||c[k]<0)throw Error("Enter valid non-negative counters and limits.");if(!Number.isInteger(c.cycles)||!Number.isInteger(c.totalCycles)||!Number.isInteger(c.cLimit)||!Number.isInteger(c.retireCycles))throw Error("Cycles and cycle limits must be whole numbers.");if(c.hLimit<=0||c.cLimit<=0||c.retireHours<=0||c.retireCycles<=0)throw Error("Limits must be greater than zero.");if(c.totalHours<c.hours||c.totalCycles<c.cycles)throw Error("Total since-new usage cannot be less than since-overhaul usage.");if(!c.release||!c.originJob||!/^\d{4}-\d{2}-\d{2}$/.test(c.due)||!/^\d{4}-\d{2}-\d{2}$/.test(c.lastOverhaul))throw Error("Enter release, origin job and valid dates.");if(c.lastOverhaul>demoDate||c.due<=c.lastOverhaul)throw Error("Overhaul cannot be in the future; removal must follow overhaul.");return c;}
function saveReceipt(){if(!technicalRole(["stores"]))return;const c={sn:$("receiptSerial").value.trim().toUpperCase(),pn:$("receiptPart").value,release:$("receiptRelease").value.trim(),originJob:$("receiptJob").value.trim(),hours:Number($("receiptHours").value),cycles:Number($("receiptCycles").value),totalHours:Number($("receiptTotalHours").value),totalCycles:Number($("receiptTotalCycles").value),hLimit:Number($("receiptHourLimit").value),cLimit:Number($("receiptCycleLimit").value),retireHours:Number($("receiptRetireHours").value),retireCycles:Number($("receiptRetireCycles").value),due:$("receiptDue").value,lastOverhaul:$("receiptOverhaul").value,reg:"Stores",position:"Receiving quarantine",condition:"Quarantined",basis:"overhaul",authority:"Pending quality review",rectification:"Received, inspection pending",modState:"Not yet verified",releaseDate:demoDate};c.flights=c.cycles;c.totalFlights=c.totalCycles;c.fLimit=c.cLimit;try{validateReceipt(c);}catch(e){$("receiptError").textContent=e.message;return;}STORE.components.push(c);STORE.parts.find(p=>p.pn===c.pn).stock++;recordMovement("Received",c,"Supplier","Stores quarantine",c.originJob);closeModal();route("#lifecycle");}
function canQualityApprove(c){if(c.reg!=="Stores"||c.condition!=="Quarantined")throw Error("Only quarantined store components can be inspected.");if(componentState(c).status==="OVERDUE")throw Error("A component with an exhausted limit cannot become serviceable.");if(!c.release)throw Error("A release reference is required.");return true;}
function openQuality(sn){if(!technicalRole(["inspector"]))return;const c=STORE.components.find(x=>x.sn===sn);engineeringModal("Quality inspection",`<form onsubmit="event.preventDefault();saveQuality('${sn}')"><p><b>${esc(c.sn)}</b> · ${esc(c.pn)}</p><label><input id="qualityDocument" type="checkbox" required> Release reference checked against sample documentation</label><label><input id="qualityPhysical" type="checkbox" required> Identity and physical condition checked</label><label for="qualityNotes">Inspection notes</label><input id="qualityNotes" required maxlength="160"><p id="qualityError" role="alert" class="field-err"></p><button type="submit" class="btn-primary">Record serviceable inspection</button></form>`);}
function saveQuality(sn){if(!technicalRole(["inspector"]))return;const c=STORE.components.find(x=>x.sn===sn);try{canQualityApprove(c);}catch(e){$("qualityError").textContent=e.message;return;}if(!$("qualityDocument").checked||!$("qualityPhysical").checked||!$("qualityNotes").value.trim())return;c.condition="Serviceable";c.position="Serviceable stores";c.rectification=$("qualityNotes").value.trim();c.inspectedBy=session.user;c.inspectedAt=new Date().toISOString();c.authority=profileOf(session.user).authority;recordMovement("Quality inspected",c,"Quarantine","Serviceable stores",c.release);closeModal();route("#lifecycle");}
function validateInstall(c,reg,position,components=STORE.components){if(c.reg!=="Stores"||c.condition!=="Serviceable"||!c.inspectedBy)throw Error("Installation requires a serviceable component with a recorded quality inspection.");if(componentState(c).status==="OVERDUE")throw Error("An expired component cannot be installed.");if(!STORE.fleet.some(a=>a.reg===reg)||!position.trim())throw Error("Select an aircraft and installation position.");if(components.some(x=>x.sn!==c.sn&&x.reg===reg&&x.position.trim().toLowerCase()===position.trim().toLowerCase()))throw Error("The aircraft position is occupied. Remove the installed serial first.");return true;}
function openInstall(sn){if(!requireEngineer())return;engineeringModal("Install component",`<form onsubmit="event.preventDefault();saveInstall('${sn}')"><p>Serial <b>${esc(sn)}</b></p><label for="installReg">Aircraft</label><select id="installReg">${STORE.fleet.map(a=>`<option>${a.reg}</option>`).join("")}</select><label for="installPosition">Installation position</label><input id="installPosition" required maxlength="60" placeholder="e.g. LH main gear"><label for="installWork">Work order / fitment reference</label><input id="installWork" required maxlength="60"><p id="installError" role="alert" class="field-err"></p><button class="btn-primary" type="submit">Record installation</button></form>`);}
function saveInstall(sn){if(!requireEngineer())return;const c=STORE.components.find(x=>x.sn===sn),reg=$("installReg").value,position=$("installPosition").value.trim(),ref=$("installWork").value.trim();try{validateInstall(c,reg,position);if(!ref)throw Error("Enter a fitment reference.");const p=STORE.parts.find(p=>p.pn===c.pn);if(!p||p.stock<1)throw Error("No stock is available.");p.stock--;}catch(e){$("installError").textContent=e.message;return;}c.reg=reg;c.position=position;c.condition="Installed";c.fittedAt=new Date().toISOString();c.fittedBy=session.user;recordMovement("Installed",c,"Serviceable stores",`${reg} / ${position}`,ref);closeModal();route("#lifecycle");}
function openRemoval(sn){if(!requireEngineer())return;engineeringModal("Remove component",`<form onsubmit="event.preventDefault();saveRemoval('${sn}')"><p>Serial <b>${esc(sn)}</b> will return to quarantine. Life counters are preserved.</p><label for="removeReason">Removal reason</label><input id="removeReason" required maxlength="160"><label for="removeWork">Work order / removal reference</label><input id="removeWork" required maxlength="60"><button class="btn-primary" type="submit">Record removal to quarantine</button></form>`);}
function saveRemoval(sn){if(!requireEngineer())return;const c=STORE.components.find(x=>x.sn===sn);if(!c||c.reg==="Stores")return;const reason=$("removeReason").value.trim(),ref=$("removeWork").value.trim();if(!reason||!ref)return;const from=`${c.reg} / ${c.position}`;c.removedFrom=c.reg;c.removedAt=new Date().toISOString();c.removalReason=reason;c.reg="Stores";c.position="Removal quarantine";c.condition="Quarantined";delete c.inspectedBy;const p=STORE.parts.find(p=>p.pn===c.pn);recordMovement("Removed",c,from,"Stores quarantine",ref);closeModal();route("#lifecycle");}
function viewDefects(){
 $("viewSub").textContent="Aircraft technical log: record defects, ground-affecting holds and rectification history.";
 $("viewActions").innerHTML=session.role==="engineer"?`<button class="btn btn-accent" onclick="openDefect()">+ Record defect</button>`:"";
 $("viewBody").innerHTML=engPanel("Aircraft defect register",engTable(["Reference / Aircraft","System / Defect","Priority","Status","Logged by","Action"],STORE.defects.map(d=>`<tr><td><b>${esc(d.ref)}</b><small class="table-sub">${esc(d.reg)}</small></td><td>ATA ${esc(d.ata)}<small class="table-sub">${esc(d.description)}</small></td><td>${engTag(d.priority,d.priority==="Grounded"?"danger":"warnb")}</td><td>${engTag(d.status,d.status==="Rectified"?"ok":"info")}<small class="table-sub">${esc(d.rectification||"")}</small></td><td>${esc(profileOf(d.by)?.name||d.by)}</td><td>${d.status==="Open"&&session.role==="engineer"?`<button class="btn btn-sm" onclick="openRectification('${d.ref}')">Rectify</button>`:"—"}</td></tr>`).join("")))+`<p class="form-note">Rectification records and planning assessments do not issue a certificate of release to service.</p>`;
}
function openDefect(){if(!requireEngineer())return;engineeringModal("Record aircraft defect",`<form onsubmit="event.preventDefault();saveDefect()"><label for="defectReg">Aircraft</label><select id="defectReg">${STORE.fleet.map(a=>`<option>${a.reg}</option>`).join("")}</select><label for="defectAta">ATA chapter</label><select id="defectAta">${Object.entries(ATA_CHAPTERS).map(([k,v])=>`<option value="${k}">${k} · ${v}</option>`).join("")}</select><label for="defectDescription">Defect description</label><input id="defectDescription" required maxlength="180"><label for="defectPriority">Technical effect</label><select id="defectPriority"><option>Grounded</option><option>Maintenance review</option></select><button type="submit" class="btn-primary">Save technical log</button></form>`);}
function saveDefect(){if(!requireEngineer())return;const description=$("defectDescription").value.trim();if(!description)return;const d={ref:`DEF-${Date.now()}`,reg:$("defectReg").value,ata:$("defectAta").value,description,priority:$("defectPriority").value,status:"Open",by:session.user,at:new Date().toISOString()};STORE.defects.unshift(d);auditOps("Defect recorded",d.ref,`${d.reg}: ${description}`);closeModal();route("#defects");}
function openRectification(ref){if(!requireEngineer())return;engineeringModal("Record rectification",`<form onsubmit="event.preventDefault();saveRectification('${ref}')"><label for="rectifyNote">Work carried out</label><input id="rectifyNote" required maxlength="180"><label for="rectifyRef">Work order / supporting record</label><input id="rectifyRef" required maxlength="60"><button type="submit" class="btn-primary">Save rectification record</button></form>`);}
function saveRectification(ref){if(!requireEngineer())return;const d=STORE.defects.find(x=>x.ref===ref),note=$("rectifyNote").value.trim(),record=$("rectifyRef").value.trim();if(!d||!note||!record)return;d.status="Rectified";d.rectification=note;d.record=record;d.rectifiedBy=session.user;d.rectifiedAt=new Date().toISOString();auditOps("Defect rectified",ref,`${record}: ${note}`);closeModal();route("#defects");}
const baseAircraftState=aircraftState;
aircraftState=function(a){if(STORE.defects.some(d=>d.reg===a.reg&&d.status==="Open"&&d.priority==="Grounded"))return "TECHNICAL HOLD";if(a.due<=0)return "CHECK DUE";return baseAircraftState(a);};
function forecastComponent(c,hoursPerDay,cyclesPerDay){const s=componentState(c),candidates=[{basis:"Calendar",days:s.days}];if(hoursPerDay>0)candidates.push({basis:"Hours",days:s.hours/hoursPerDay});if(cyclesPerDay>0){candidates.push({basis:"Cycles",days:s.cycles/cyclesPerDay});if(s.flights!==null)candidates.push({basis:"Flights",days:s.flights/cyclesPerDay});}const first=candidates.reduce((a,b)=>a.days<=b.days?a:b);const days=Math.max(0,Math.floor(first.days));return {basis:first.basis,days,date:relativeDate(days),status:s.status};}
function flightAssessment(reg,hours,cycles,date){const a=STORE.fleet.find(x=>x.reg===reg),reasons=[];if(!a)return ["Unknown aircraft"];if(!Number.isFinite(hours)||!Number.isInteger(cycles)||hours<0||cycles<0||!date)return ["Invalid planned flight input"];if(aircraftState(a)!=="NO ACTIVE HOLD")reasons.push(aircraftState(a));if(hours>=a.due)reasons.push("Planned flight reaches scheduled aircraft check limit");for(const c of STORE.components.filter(x=>x.reg===reg)){const s=componentState(c);if(hours>=s.hours||cycles>=s.cycles||s.flights!==null&&cycles>=s.flights||date>=c.due)reasons.push(`${c.sn}: planned flight reaches a component limit`);}if(STORE.defects.some(d=>d.reg===reg&&d.status==="Open"))reasons.push("Open defect requires maintenance review");return [...new Set(reasons)];}
function viewForecastPlanning(){
 $("viewSub").textContent="Calculate forecast removal dates and assess a planned flight against the current technical records. Rates are editable planning assumptions.";
 $("viewActions").innerHTML=`<button class="btn" onclick="exportTechnical()">Export technical records</button>`;
 const rates=STORE.planningRates;
 $("viewBody").innerHTML=`${engPanel("Utilisation assumptions",`<div class="rate-grid">${STORE.fleet.map(a=>{const r=rates[a.reg]||{hours:4,cycles:2};return `<div class="rate-card"><b>${a.reg}</b><label for="rateH-${a.reg}">Flight hours / day</label><input id="rateH-${a.reg}" type="number" min="0" step="0.1" value="${r.hours}" oninput="updateForecast('${a.reg}')"><label for="rateC-${a.reg}">Cycles / day</label><input id="rateC-${a.reg}" type="number" min="0" step="0.1" value="${r.cycles}" oninput="updateForecast('${a.reg}')"></div>`;}).join("")}</div>`)}<div style="margin-top:20px">${engPanel("Maintenance due forecast",engTable(["Serial / Aircraft","Remaining FH / FC","Forecast removal","Controlling parameter","Action"],""))}</div><div style="margin-top:20px">${engPanel("Planned-flight technical assessment",`<form onsubmit="event.preventDefault();assessFlight()" class="form-grid"><div><label for="assessReg">Aircraft</label><select id="assessReg">${STORE.fleet.map(a=>`<option>${a.reg}</option>`).join("")}</select></div><div><label for="assessH">Planned flight hours</label><input id="assessH" type="number" min="0" step="0.1" value="2" required></div><div><label for="assessC">Planned cycles / flights</label><input id="assessC" type="number" min="0" value="1" required></div><div><label for="assessDate">Flight date</label><input id="assessDate" type="date" value="${demoDate}" required></div><button type="submit" class="btn btn-accent">Assess planned flight</button></form><div id="assessmentResult" aria-live="polite"></div><p class="form-note">Planning decision support only; no dispatch or airworthiness release is issued.</p>`)}</div>`;renderDueForecast();
}
function updateForecast(reg){const h=Number($("rateH-"+reg).value),c=Number($("rateC-"+reg).value);if(!Number.isFinite(h)||!Number.isFinite(c)||h<0||c<0)return;STORE.planningRates[reg]={hours:h,cycles:c};persistOps();renderDueForecast();}
function renderDueForecast(){const rows=STORE.components.filter(c=>c.reg!=="Stores").map(c=>{const r=STORE.planningRates[c.reg]||{hours:4,cycles:2},f=forecastComponent(c,r.hours,r.cycles),s=componentState(c);return `<tr><td><b>${esc(c.sn)}</b><small class="table-sub">${esc(c.reg)} · ${esc(c.pn)}</small></td><td>${s.hours.toLocaleString()} FH / ${s.cycles} FC</td><td>${f.date}<small class="table-sub">${f.days===null?"Condition monitoring required":f.days+" planned operating days"}</small></td><td>${engTag(f.basis,f.days!==null&&f.days<14?"warnb":"info")}</td><td>${session.role==="engineer"?`<button class="btn btn-sm" onclick="planFromComponent('${c.sn}')">Plan removal</button>`:"—"}</td></tr>`;}).join("");$("viewBody").querySelector("tbody").innerHTML=rows;}
function planFromComponent(sn){const c=STORE.components.find(x=>x.sn===sn);openPlan();if(!$("planTask"))return;$("planTask").value=`Component removal: ${c.sn}`;$("planReg").value=c.reg;const r=STORE.planningRates[c.reg]||{hours:4,cycles:2},f=forecastComponent(c,r.hours,r.cycles);$("planStart").value=f.date+"T08:00";$("planEnd").value=f.date+"T12:00";}
function assessFlight(){const reasons=flightAssessment($("assessReg").value,Number($("assessH").value),Number($("assessC").value),$("assessDate").value);$("assessmentResult").innerHTML=`<div class="assessment ${reasons.length?"hold":"clear"}"><b>${reasons.length?"Maintenance review required":"No limit conflict found in demo records"}</b>${reasons.length?`<ul>${reasons.map(r=>`<li>${esc(r)}</li>`).join("")}</ul>`:"<p>Planned usage stays within the recorded limits.</p>"}</div>`;}
function exportTechnical(){const data={schema:"tslms-technical-demo-v1",exportedAt:new Date().toISOString(),fleet:STORE.fleet,components:STORE.components,plans:STORE.jobs,movements:STORE.movements,defects:STORE.defects,audit:STORE.audit};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="tslms-technical-records.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
