const fs=require('fs'),vm=require('vm'),path=require('path');const memory={};const ctx=vm.createContext({console,Date,setTimeout:fn=>fn(),Blob:class{constructor(parts){memory.export=JSON.parse(parts[0]);}},URL:{createObjectURL:()=> 'blob:demo',revokeObjectURL(){}},document:{createElement:()=>({click(){memory.clicked=true;}})},localStorage:{getItem:k=>memory[k]||null,setItem:(k,v)=>memory[k]=v},doLogin(){},savePlan(){},advancePlan(){},session:{user:'k.moyo',role:'inspector'},toast(){}});
for(const f of ['core','engineering','operations','technical','quality'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..','js',f+'.js'),'utf8'),ctx,{filename:f});
vm.runInContext(`
const check=(x,m)=>{if(!x)throw Error(m)},throws=(fn,m)=>{let failed=false;try{fn()}catch(e){failed=true}check(failed,m)};
check(calibrationScreen(3,1,4),'inclusive tolerance boundary');check(!calibrationScreen(3.01,1,4),'uncertainty guard');throws(()=>calibrationScreen(1,-1,4),'negative uncertainty');throws(()=>calibrationScreen(NaN,1,4),'nonfinite');
check(currentCalibration('TOOL-2').usable,'valid torque tool');check(!currentCalibration('TOOL-2',relativeDate(14)).usable,'due-day block');check(!currentCalibration('TOOL-1').usable,'missing cert block');check(!currentCalibration('TOOL-3').usable,'out of service');
const cal={...STORE.calibrations[0],id:'TEST',date:demoDate,due:relativeDate(365),found:5,left:0,at:new Date().toISOString()};STORE.jobs[0].status='Complete';check(addCalibration(cal),'as-found failure');check(STORE.qualityFindings[0].affected.includes('WO-24518'),'work impact lookup');check(!currentCalibration('TOOL-2').usable,'open impact review blocks');STORE.qualityFindings[0].status='Closed';check(currentCalibration('TOOL-2').usable,'passing as-left plus closed review');addCalibration({...cal,found:0,left:9,id:'FAIL'});check(!currentCalibration('TOOL-2').usable,'as-left failure quarantines');throws(()=>addCalibration({...cal,date:relativeDate(1)}),'future calibration rejected');
const c=STORE.components[2];check(lifeReviewState(c)==='Awaiting inspection','initial queue');recordLifeReview(c,'Verified','LOG-DEMO','Reconciled');check(lifeReviewState(c)==='Reviewed current record','verified snapshot');c.hours++;check(lifeReviewState(c)==='Changed since inspection','counter change invalidation');recordLifeReview(c,'Discrepancy','LOG-ERR','Missing evidence');c.hours++;check(lifeReviewState(c)==='Discrepancy open','discrepancy survives usage');check(aircraftState(STORE.fleet[2])==='QUALITY HOLD','quality hold');check(flightAssessment(c.reg,1,1,demoDate).includes('Unresolved inspector life-record discrepancy'),'flight review gate');recordLifeReview(c,'Verified','LOG-RESOLVED','Evidence reconciled');check(lifeReviewState(c)==='Reviewed current record','new inspector review resolves');throws(()=>recordLifeReview({...c,hours:c.hLimit},'Verified','DOC','Expired'),'expired cannot verify');
const store={...c,sn:'STORE-TEST',reg:'Stores',condition:'Serviceable',inspectedBy:'k.moyo',position:'Stores'};throws(()=>validateInstall(store,'Z-WRH','System B',[]),'life-review required for fitment');recordLifeReview(store,'Verified','STORE-LOG','Reconciled');check(validateInstall(store,'Z-WRH','System B',[]),'fitment after independent life review');STORE.labTests.unshift({sn:store.sn,report:'LAB-R1',result:'Action needed',status:'Report recorded'});throws(()=>validateInstall(store,'Z-WRH','System B',[]),'adverse report fitment block');throws(()=>canQualityApprove({...store,condition:'Quarantined'}),'adverse report stores quarantine');STORE.labTests.unshift({sn:store.sn,report:'LAB-R2',result:'No adverse finding',status:'Report recorded'});check(adverseLabOpen(store.sn),'clean report needs inspector disposition');STORE.labTests[0].status='Reviewed';check(!adverseLabOpen(store.sn),'reviewed follow-up result');throws(()=>validateCalibration({...cal,due:'2027-02-30'}),'invalid calendar date');persistOps();check(JSON.parse(localStorage.getItem(OPS_KEY)).lifeReviews.length===STORE.lifeReviews.length,'quality persistence');
`,ctx);vm.runInContext('exportTechnical()',ctx);if(!memory.clicked||memory.export.schema!=='tslms-technical-demo-v2'||!Array.isArray(memory.export.calibrations)||!Array.isArray(memory.export.labTests)||!Array.isArray(memory.export.lifeReviews))throw Error('record pack export');console.log('PASS: calibration boundaries, expiry, impact lookup, quarantines, snapshot staleness, persistent discrepancies, quality hold, installation and persistence.');
